-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-13 21:29:12 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE adresy (
    id_adresu     INTEGER NOT NULL,
    ulica         VARCHAR2(64),
    nr_domu       INTEGER,
    kod_pocztowy  VARCHAR2(64),
    miejscowosc   VARCHAR2(64)
);

ALTER TABLE adresy ADD CONSTRAINT adresy_pk PRIMARY KEY ( id_adresu );

CREATE TABLE konta (
    login  INTEGER NOT NULL,
    haslo  VARCHAR2(64)
);

ALTER TABLE konta ADD CONSTRAINT konta_pk PRIMARY KEY ( login );

CREATE TABLE lekarze (
    id_lekarza     INTEGER NOT NULL,
    imie           VARCHAR2(64),
    nazwisko       VARCHAR2(64),
    pesel          INTEGER,
    telefon        INTEGER,
    specjalizacja  VARCHAR2(64)
);

ALTER TABLE lekarze ADD CONSTRAINT lekarze_pk PRIMARY KEY ( id_lekarza );

CREATE TABLE pacjenci (
    id_pacjenta  INTEGER NOT NULL,
    imie         VARCHAR2(64),
    nazwisko     VARCHAR2(64),
    pesel        INTEGER,
    telefon      INTEGER
);

ALTER TABLE pacjenci ADD CONSTRAINT pacjenci_pk PRIMARY KEY ( id_pacjenta );

CREATE TABLE wizyty (
    id_wizyty  INTEGER NOT NULL,
    data       DATE,
    godzina    DATE
);

ALTER TABLE wizyty ADD CONSTRAINT wizyty_pk PRIMARY KEY ( id_wizyty );

ALTER TABLE lekarze
    ADD CONSTRAINT lekarze_adresy_fk FOREIGN KEY ( id_lekarza )
        REFERENCES adresy ( id_adresu );

ALTER TABLE lekarze
    ADD CONSTRAINT lekarze_konta_fk FOREIGN KEY ( id_lekarza )
        REFERENCES konta ( login );

ALTER TABLE pacjenci
    ADD CONSTRAINT pacjenci_adresy_fk FOREIGN KEY ( id_pacjenta )
        REFERENCES adresy ( id_adresu );

ALTER TABLE pacjenci
    ADD CONSTRAINT pacjenci_konta_fk FOREIGN KEY ( id_pacjenta )
        REFERENCES konta ( login );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_lekarze_fk FOREIGN KEY ( id_wizyty )
        REFERENCES lekarze ( id_lekarza );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_pacjenci_fk FOREIGN KEY ( id_wizyty )
        REFERENCES pacjenci ( id_pacjenta );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
